import type { Student } from "../types";

export const SAMPLE_STUDENTS: Student[] = [
  {
    id: "student-1",
    name: "田中太郎",
    furigana: "たなかたろう",
    gender: "male",
    studentNumber: 1,
    roleIds: ["role-class-leader"],
  },
  {
    id: "student-2",
    name: "佐藤花子",
    furigana: "さとうはなこ",
    gender: "female",
    studentNumber: 2,
    roleIds: ["role-vice-leader"],
  },
  {
    id: "student-3",
    name: "鈴木次郎",
    furigana: "すずきじろう",
    gender: "male",
    studentNumber: 3,
    roleIds: [],
  },
  {
    id: "student-4",
    name: "高橋美咲",
    furigana: "たかはしみさき",
    gender: "female",
    studentNumber: 4,
    roleIds: [],
  },
  {
    id: "student-5",
    name: "伊藤健太",
    furigana: "いとうけんた",
    gender: "male",
    studentNumber: 5,
    roleIds: [],
  },
  {
    id: "student-6",
    name: "山田一郎",
    furigana: "やまだいちろう",
    gender: "male",
    studentNumber: 6,
    roleIds: [],
  },
  {
    id: "student-7",
    name: "中村花子",
    furigana: "なかむらはなこ",
    gender: "female",
    studentNumber: 7,
    roleIds: [],
  },
  {
    id: "student-8",
    name: "小林三郎",
    furigana: "こばやしさぶろう",
    gender: "male",
    studentNumber: 8,
    roleIds: [],
  },
  {
    id: "student-9",
    name: "加藤美咲",
    furigana: "かとうみさき",
    gender: "female",
    studentNumber: 9,
    roleIds: [],
  },
  {
    id: "student-10",
    name: "吉田健太",
    furigana: "よしだけんた",
    gender: "male",
    studentNumber: 10,
    roleIds: [],
  },
  {
    id: "student-11",
    name: "松本一郎",
    furigana: "まつもといちろう",
    gender: "male",
    studentNumber: 11,
    roleIds: [],
  },
  {
    id: "student-12",
    name: "木村花子",
    furigana: "きむらはなこ",
    gender: "female",
    studentNumber: 12,
    roleIds: [],
  },
  {
    id: "student-13",
    name: "林三郎",
    furigana: "はやしさぶろう",
    gender: "male",
    studentNumber: 13,
    roleIds: [],
  },
  {
    id: "student-14",
    name: "森美咲",
    furigana: "もりみさき",
    gender: "female",
    studentNumber: 14,
    roleIds: [],
  },
  {
    id: "student-15",
    name: "清水健太",
    furigana: "しみずけんた",
    gender: "male",
    studentNumber: 15,
    roleIds: [],
  },
  {
    id: "student-16",
    name: "斎藤一郎",
    furigana: "さいとういちろう",
    gender: "male",
    studentNumber: 16,
    roleIds: [],
  },
  {
    id: "student-17",
    name: "渡辺花子",
    furigana: "わたなべはなこ",
    gender: "female",
    studentNumber: 17,
    roleIds: [],
  },
  {
    id: "student-18",
    name: "石川三郎",
    furigana: "いしかわさぶろう",
    gender: "male",
    studentNumber: 18,
    roleIds: [],
  },
  {
    id: "student-19",
    name: "阿部美咲",
    furigana: "あべみさき",
    gender: "female",
    studentNumber: 19,
    roleIds: [],
  },
  {
    id: "student-20",
    name: "福田健太",
    furigana: "ふくだけんた",
    gender: "male",
    studentNumber: 20,
    roleIds: [],
  },
  {
    id: "student-21",
    name: "岡田一郎",
    furigana: "おかだいちろう",
    gender: "male",
    studentNumber: 21,
    roleIds: [],
  },
  {
    id: "student-22",
    name: "中島花子",
    furigana: "なかじまはなこ",
    gender: "female",
    studentNumber: 22,
    roleIds: [],
  },
  {
    id: "student-23",
    name: "藤田三郎",
    furigana: "ふじたさぶろう",
    gender: "male",
    studentNumber: 23,
    roleIds: [],
  },
  {
    id: "student-24",
    name: "村上美咲",
    furigana: "むらかみみさき",
    gender: "female",
    studentNumber: 24,
    roleIds: [],
  },
  {
    id: "student-25",
    name: "西村健太",
    furigana: "にしむらけんた",
    gender: "male",
    studentNumber: 25,
    roleIds: [],
  },
  {
    id: "student-26",
    name: "東一郎",
    furigana: "ひがしいちろう",
    gender: "male",
    studentNumber: 26,
    roleIds: [],
  },
  {
    id: "student-27",
    name: "南花子",
    furigana: "みなみはなこ",
    gender: "female",
    studentNumber: 27,
    roleIds: [],
  },
  {
    id: "student-28",
    name: "北三郎",
    furigana: "きたさぶろう",
    gender: "male",
    studentNumber: 28,
    roleIds: [],
  },
  {
    id: "student-29",
    name: "上美咲",
    furigana: "うえみさき",
    gender: "female",
    studentNumber: 29,
    roleIds: [],
  },
  {
    id: "student-30",
    name: "下健太",
    furigana: "しもけんた",
    gender: "male",
    studentNumber: 30,
    roleIds: [],
  },
  {
    id: "student-31",
    name: "前田一郎",
    furigana: "まえだいちろう",
    gender: "male",
    studentNumber: 31,
    roleIds: [],
  },
  {
    id: "student-32",
    name: "後藤花子",
    furigana: "ごとうはなこ",
    gender: "female",
    studentNumber: 32,
    roleIds: [],
  },
  {
    id: "student-33",
    name: "左藤三郎",
    furigana: "さとうさぶろう",
    gender: "male",
    studentNumber: 33,
    roleIds: [],
  },
  {
    id: "student-34",
    name: "右田美咲",
    furigana: "みぎたみさき",
    gender: "female",
    studentNumber: 34,
    roleIds: [],
  },
  {
    id: "student-35",
    name: "中央健太",
    furigana: "ちゅうおうけんた",
    gender: "male",
    studentNumber: 35,
    roleIds: [],
  },
  {
    id: "student-36",
    name: "外側一郎",
    furigana: "そとがわいちろう",
    gender: "male",
    studentNumber: 36,
    roleIds: [],
  },
  {
    id: "student-37",
    name: "内側花子",
    furigana: "うちがわはなこ",
    gender: "female",
    studentNumber: 37,
    roleIds: [],
  },
  {
    id: "student-38",
    name: "上側三郎",
    furigana: "うえがわさぶろう",
    gender: "male",
    studentNumber: 38,
    roleIds: [],
  },
  {
    id: "student-39",
    name: "下側美咲",
    furigana: "したがわみさき",
    gender: "female",
    studentNumber: 39,
    roleIds: [],
  },
];
