import { Student } from "../types";

/**
 * デバッグ用の生徒データを生成
 * @returns デバッグ用生徒配列
 */
export const createDebugStudents = (): Student[] => {
  return [
    {
      id: "student-1",
      name: "田中太郎",
      furigana: "たなかたろう",
      gender: "male" as const,
      studentNumber: 1,
      roleIds: [],
    },
    {
      id: "student-2",
      name: "佐藤花子",
      furigana: "さとうはなこ",
      gender: "female" as const,
      studentNumber: 2,
      roleIds: [],
    },
    {
      id: "student-3",
      name: "鈴木次郎",
      furigana: "すずきじろう",
      gender: "male" as const,
      studentNumber: 3,
      roleIds: [],
    },
    {
      id: "student-4",
      name: "高橋美咲",
      furigana: "たかはしみさき",
      gender: "female" as const,
      studentNumber: 4,
      roleIds: [],
    },
    {
      id: "student-5",
      name: "伊藤健太",
      furigana: "いとうけんた",
      gender: "male" as const,
      studentNumber: 5,
      roleIds: [],
    },
    {
      id: "student-6",
      name: "渡辺さくら",
      furigana: "わたなべさくら",
      gender: "female" as const,
      studentNumber: 6,
      roleIds: [],
    },
    {
      id: "student-7",
      name: "山本大輔",
      furigana: "やまもとだいすけ",
      gender: "male" as const,
      studentNumber: 7,
      roleIds: [],
    },
    {
      id: "student-8",
      name: "中村優子",
      furigana: "なかむらゆうこ",
      gender: "female" as const,
      studentNumber: 8,
      roleIds: [],
    },
    {
      id: "student-9",
      name: "小林翔太",
      furigana: "こばやししょうた",
      gender: "male" as const,
      studentNumber: 9,
      roleIds: [],
    },
    {
      id: "student-10",
      name: "加藤愛美",
      furigana: "かとうまなみ",
      gender: "female" as const,
      studentNumber: 10,
      roleIds: [],
    },
    {
      id: "student-11",
      name: "吉田直樹",
      furigana: "よしだなおき",
      gender: "male" as const,
      studentNumber: 11,
      roleIds: [],
    },
    {
      id: "student-12",
      name: "松本麻衣",
      furigana: "まつもとまい",
      gender: "female" as const,
      studentNumber: 12,
      roleIds: [],
    },
    {
      id: "student-13",
      name: "井上雄介",
      furigana: "いのうえゆうすけ",
      gender: "male" as const,
      studentNumber: 13,
      roleIds: [],
    },
    {
      id: "student-14",
      name: "木村由美",
      furigana: "きむらゆみ",
      gender: "female" as const,
      studentNumber: 14,
      roleIds: [],
    },
    {
      id: "student-15",
      name: "林健一",
      furigana: "はやしけんいち",
      gender: "male" as const,
      studentNumber: 15,
      roleIds: [],
    },
    {
      id: "student-16",
      name: "清水美穂",
      furigana: "しみずみほ",
      gender: "female" as const,
      studentNumber: 16,
      roleIds: [],
    },
    {
      id: "student-17",
      name: "山口拓也",
      furigana: "やまぐちたくや",
      gender: "male" as const,
      studentNumber: 17,
      roleIds: [],
    },
    {
      id: "student-18",
      name: "池田理恵",
      furigana: "いけだりえ",
      gender: "female" as const,
      studentNumber: 18,
      roleIds: [],
    },
    {
      id: "student-19",
      name: "前田和也",
      furigana: "まえだかずや",
      gender: "male" as const,
      studentNumber: 19,
      roleIds: [],
    },
    {
      id: "student-20",
      name: "藤原香織",
      furigana: "ふじわらかおり",
      gender: "female" as const,
      studentNumber: 20,
      roleIds: [],
    },
  ];
};
